### PR TITLE
Bump match inner block indent a level

### PR DESCRIPTION
**Pull request by marcusklaas**
Fix https://github.com/nrc/rustfmt/issues/496.

### CODE REVIEW

**Comment by marcusklaas** [comment]
Fix https://github.com/nrc/rustfmt/issues/494.

**Comment by nrc** [comment]
I think that we should apply the rule that if we have a multiple line arm body, then we use `{}`, even if it is just a single expression. That could be an option, in which case we should take this PR as is and add that option on top, or it could just happen.

This PR looks good as is, so r+, but I'll not merge in case you have thoughts about the multi-line/`{}` thing.

**Comment by marcusklaas** [comment]
Agreed 100%. I've even created an issue for it. It's just a bit more work so I thought we'd do this first.

-----Original Message-----

**Comment by nrc** [comment]
Cool, sounds good. Lets merge this now then.

**Pull request merged**
