### PR TITLE
Format if expressions & loops

### PR DESCRIPTION
**Pull request by marcusklaas**
Since a lot of code is inside these expressions, this should significantly increase coverage!

Blocked by https://github.com/rust-lang/rust/pull/27065.

Single line if-else expressions are not implemented yet.

Closes https://github.com/nrc/rustfmt/issues/102.

### CODE REVIEW

**Comment by nrc** [comment]
I wonder if we should ever try to format the label on to the previous line? For example:

```
'a_long_label:
while a < b {
}

// rather than 
'a_long_label: while a <
                   b {
}
```

(assuming a and b are actually really long, or whatever).

I guess in practice labels are usually quite short, but it does prevent rightward drift a little bit.

Anyway, just a random thought, don't need to change anything with the PR.

**Comment by nrc** [comment]
This is awesome, thanks!

**Comment by marcusklaas** [comment]
Good thing you mentioned tests for ranges, because their bad spans still break this :-(

It seems we're blocked on https://github.com/rust-lang/rust/issues/27162 now.

**Comment by marcusklaas** [comment]
How should we format if-else block inside functions? I'm tempted to format things as follows:
```rust
Some(if cond {
    ...
} else {
    ...
})
```
but that's not really consistent with how we format them within struct literals. OTOH,
```rust
Some(if cond {
         ...

     } else {
 
        ...

     })
```
just looks weird to me...

What to do?

**Comment by nrc** [comment]
I would add options for this: block indent, block indent + tab, visual indent.

**Comment by nrc** [comment]
I'm not sure what the default should be, perhaps block + tab?

**Comment by marcusklaas** [comment]
I'll play around with a bit, but that sounds sensible to me.

**Comment by marcusklaas** [comment]
The bad span for ranges should be fixed now, I hope nightly is updated in time!

This should also close https://github.com/nrc/rustfmt/issues/155.

**Comment by marcusklaas** [comment]
Guess not :-(

**Comment by marcusklaas** [comment]
This builds now!

**Pull request merged**
