### PR TITLE
Fix build on nightly

### PR DESCRIPTION
**Pull request by SBSTP**
https://github.com/rust-lang/rust/pull/27857

Need this for the other PR.
@marcusklaas

### CODE REVIEW

**Comment by SBSTP** [comment]
Is it possible that travis wasn't updated yet?

**Comment by marcusklaas** [comment]
That seems to be the case. It uses the nightly of August 23.

**Comment by marcusklaas** [comment]
I'll merge this as soon as travis updates its compiler. You can just include this commit in your other PR as well.

**Comment by SBSTP** [comment]
Ok

**Comment by marcusklaas** [comment]
@SBSTP, what's your `rustc --version`? I just downloaded the most recent nightly and I'm getting the same error as travis. Did you compile your compiler from source?

**Comment by SBSTP** [comment]
I use [this](https://launchpad.net/~hansjorg/+archive/ubuntu/rust) ppa. Ubuntu 15.04/Vivid. `rustc --version` just says `rustc 1.4.0-dev'. The commit was merged on the 24th, to it would be in the 25th's nightly, I think. The ppa I'm using might be ahead by a few days over the version available on the website.

**Pull request merged**
