### PR TITLE
Coverage mode for rustfmt...

### LINKED ISSUE #351: Show rustfmt coverage
It would be nice to see where we format and where we skip formatting. I think we can do this fairly easily when we format a missing span, rather than just pasting out the snippet for the span, we replace all non-whitespace chars with `X`s or emoji sad faces or something.

As a bonus, it would be great if we could (optionally) report how much of a format was skips. So after a test or run on a module, we could report - "75% of this module was rewritten". The goal would be for tests to assert we always hit 100%.

### PR DESCRIPTION
**Pull request by Wafflespeanut**
fixes #351

### CODE REVIEW

**Comment by Wafflespeanut** [comment]
@nrc I've made use of `Config` to check the write mode in `missing_spans.rs`. I'm not sure whether this is the right way, but that's the only way I could think of making this to work.

And, sorry for taking this too long :)

**Comment by Wafflespeanut** [comment]
~/rustfmt: cargo run -- tests/source/loop.rs --write-mode=coverage
         Running `target/debug/rustfmt tests/source/loop.rs --write-mode=coverage`

    tests/source/loop.rs:


    fn main() {
        loop {
            return some_val;
        }

        let x = loop {
            do_forever();
        };

        'label: loop {
            XX XXXX XXXXXXXX
        }

        'a: while loooooooooooooooooooooooooooooooooong_variable_name + another_value >
                  some_other_value {}

        while aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa > bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb {
        }

        'b: for xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx in some_iter(arg1,
                                                                                            arg2) {
            XX XX XXXX
        }

        while let Some(i) = x.find('s') {
            x.update();
            XX XXXXX XXXX
            XX XXXXXXXXX
            XX XXXXXXXX XXXXX
        }
    }

**Comment by nrc** [comment]
Awesome! That looks great!

For accessing the write mode, I think the better (still not great) way to do it is to add the `WriteMode` to `RustFmtCalls`, and to `FmtVisitor` and then check it directly in missing_spans. If you add it to the config, then it will be an option that can be set in the toml file, but which will be overwritten.

**Comment by nrc** [comment]
For testing, we'll probably need a new category of tests which uses the `Coverage` mode (we might even need a `TestCoverage` mode, I don't recall exactly how testing works). You'll probably want to add directories coverage-source and coverage-target and add a test file to each. The testing code would then just run rustfmt on the source file in Coverage mode and compare with the target file, exactly the same as we do for normal tests, just in a different WriteMode (and idempotent tests don't make sense).

**Comment by Wafflespeanut** [comment]
@nrc You're right that we could make use of `RustFmtCalls`, but instead of having the `WriteMode` everywhere, I made use of a bool, as it looked cleaner. Because we can check whether we're in coverage mode right away and pass the bool. Anyways, I've updated the PR, tests are on their way :)

**Comment by Wafflespeanut** [comment]
@nrc I've included a sample test. Not sure whether this is what you want, because I've just updated the existing tests with another function (and tweaks for it) to test for coverage mode. r?

**Comment by nrc** [comment]
I would prefer to pass the coverage mode rather than a bool - bools are generally a bit obscure - equivalent to using ints instead of a c-style enum. Using an enum instead is more self-documenting (since you always name the intention, you don't need to look at the function def to know what it's used for) and reduces errors (you won't mix the Coverge mode with some other bool).

Otherwise the PR looks good. r+ with the two bool changes

**Comment by marcusklaas** [comment]
Should we also XXX things that are produced by the snippet method in either `RewriteContext` or `FmtVisitor`?

**Comment by nrc** [comment]
@marcusklaas yeah, we should. We could do it as a follow-up.

**Comment by Wafflespeanut** [comment]
@nrc enum over bool - Agreed, will do it :)

**Comment by Wafflespeanut** [comment]
@nrc r?

**Comment by nrc** [comment]
r+ Thanks for making all the changes!

Needs a rebase before merge though.

**Comment by Wafflespeanut** [comment]
@nrc rebased, thanks :)

**Pull request merged**
