### PR TITLE
Update import list formatting

### PR DESCRIPTION
**Pull request by marcusklaas**
Adds comments and sorts items alphabetically. This is based on https://github.com/nrc/rustfmt/pull/93, to use the updated `write_list`.

### CODE REVIEW

**Comment by nrc** [comment]
I think there should be an option for alphabetical ordering - I imagine many will not want it.

**Comment by nrc** [comment]
Looks good - a few minor comments inline

**Comment by marcusklaas** [comment]
Updated the PR

**Comment by marcusklaas** [comment]
Yo @nrc I know you're mega busy but in case you've missed it: I think this PR is ready 4 prime!

**Comment by nrc** [comment]
Sorry, I did miss your comment some how

**Pull request merged**
