### PR TITLE
Disallow specifying a write mode with stdin input

### PR DESCRIPTION
**Pull request by kamalmarhubi**

### CODE REVIEW

**Comment by nrc** [comment]
I'm not sure how much benefit an error is here vs silently ignoring the write mode. @johannhof do you have an opinion?

**Comment by kamalmarhubi** [comment]
Yeah I wasn't sure either. Could see it either way...

**Comment by johannhof** [comment]
That was actually included in my initial pull request, but we removed it. We have a small precedent with `gofmt` doing the same (failing with an error on `-w` being present), but I don't have hard feelings either way.

**Comment by nrc** [comment]
Heh, ok at least I'm consistent. I think I'd rather leave it as is for now - I don't think we can do anything bad by ignoring the write mode - we're just dumping to the terminal. If this does actually cause problems or there is a good reason to be more restrictive, I'd be happy to take this later. Closing for now.

**Pull request closed without merging**
