### PR TITLE
Use a width heuristic for struct lits

### PR DESCRIPTION
**Pull request by nrc**

### CODE REVIEW

**Comment by marcusklaas** [comment]
I know arguing over default settings is the pinnacle of bikeshedding, but isn't a 12 character limit on the low side?

I feel like literals like `Seeking::Issue { todo_idx: 0, fixme_idx: 0 }` and certainly `Foo { a: 1, b: f(2), ..g(3) }` should be formatted on a single line. Maybe 20 is a more forgiving limit?

Anyway, I'll leave this to your judgement.

r+

**Comment by nrc** [comment]
Yeah, it's an interesting call. I started with 50 like functions, then went down to something like 20 and then went lower. I also thought about how many fields I want to see - and I decided with a medium sized field name and a non-trivial expression, any more than one field on a line is too much. And looking at reformatting rustc crates this seems to hold up - it is common to see two field structs on multiple lines.

I actually think one-line structs are almost always too hard to read. Of your two examples, I'd like the first one on two lines and the second on one line, but I don't think that can be done in the current scheme.

One thing I was thinking of was that we could exclude the initialiser from the count, I'll see if that is easy.

(btw, the limit does not include spacing or punctuation between fields, so it is not quite as struct as it seems).

**Comment by marcusklaas** [comment]
> not quite as struct

:100:

**Comment by nrc** [comment]
lol, it's early!

**Comment by marcusklaas** [comment]
Haha I thought it was a pun ;-)

**Comment by nrc** [comment]
Hmm, so excluding the initialiser would be a pain, so lets not do that.

**Pull request merged**
