### PR TITLE
Fix doc comment regression and add tests.

### LINKED ISSUE #502: Long doc comments are incorrectly reformatted as regular comments
Example:
```
Mismatch at tests/target/lib.rs:1:
+// ! This is a long line that angers rustfmt. Rustfmt shall deal with it⏎
+// swiftly and justly.⏎
-//! This is a long line that angers rustfmt. Rustfmt shall deal with it swiftly and justly.⏎
 extern crate foo;⏎
```

I believe e8447a82104d5f9da2802af1e8530aba7ad6512a introduced the problem.

### PR DESCRIPTION
**Pull request by tikue**
Fixes #502.

I tried to follow the code style already present.

### CODE REVIEW

**Comment by killercup** [comment]
You might want to expand you test cases to include multiple long lines, e.g.:

Source:

```rust
/// Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
/// Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
/// Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
/// Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```

Target:

```rust
/// Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
/// labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
/// laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
/// voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
/// cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```

**Comment by marcusklaas** [comment]
These are tough, @killercup. As it currently stands, we don't format the entire comment as a single piece of text, but rather format comments line by line. This is to preserve significant whitespace in comments that are not plain text.

Otherwise, we would scramble comments such as the one below:
```rust
// A description of a table which runs a bit looooooooooooooooooooooooooooooooooooooooong
//                 o        This graph demonstrates how
//                / \       significant whitespace is
//               o   o      preserved.
//              /|\   \
//             o o o   o
```

If a good solution or compromise can be found, I'd gladly take that instead.

**Comment by marcusklaas** [comment]
Thanks for the PR!

**Comment by killercup** [comment]
Good point, @marcusklaas. What about adding the line re-wrapping only for doc comments? Assuming those need to be Markdown, it shouldn't change the output. Your example would work, as soon as you add an empty line before the graph (as it will then be treated as a code block). There might also already be a line-rewrapping algorithms for markdown out there that could be used by rustfmt (pandoc supports this and doesn't seem to break any special stuff like code or tables).

**Comment by tikue** [comment]
I am in favor of line re-wrapping. I was going to look into it before this pr, but since this issue was breaking code in the wild (read: my code) I figured I'd do it sooner rather than later. Rustfmt already provides a way to opt a few lines out of formatting, right? So worst case, you simply mark the comment you don't want reformatted.

**Comment by marcusklaas** [comment]
Unfortunately, it doesn't work that way for comments. We can only place `#[rustfmt_skip]` on items.

That's alright, though. The only issue here is how to format overly long lines in rustfmt. Once a line has been corrected, either by rustfmt or by hand, it won't be touched afterwards.

I guess it makes sense to rewrap by default. Plain old text comments are probably a lot more common than comments with significant whitespace. If you'd like to work on that, that would be great!

**Comment by tikue** [comment]
There's some prior art here, actually. Intellij -- and I believe eclipse as well -- offer a special configurable note you can put in a comment for exactly this purpose:

```
// @formatter:off
//     special
//             formatting
// @formatter:on

**Comment by tikue** [comment]
I probably won't have time to work on this for a while, unfortunately. Busy few weeks ahead of me.

**Comment by tikue** [comment]
I've been playing around with re-wrapping lines by default, and I'm starting to think it'd be more annoying than helpful in most cases.

Take tests/source/fn-custom-2.rs, for instance. It starts with the following comments:
```
// rustfmt-fn_arg_indent: Inherit
// rustfmt-generics_indent: Tabbed
// rustfmt-where_indent: Inherit
// rustfmt-where_layout: Mixed
// Test different indents.
```

Line re-wrapping by default turns this into something like this:
```
// rustfmt-fn_arg_indent: Inherit rustfmt-generics_indent: Tabbed 
// rustfmt-where_indent: Inherit rustfmt-where_layout: Mixed Test
// different indents.
```

Even the copyright message gets messed up:

Before
```
-// Copyright 2015 The Rust Project Developers. See the COPYRIGHT⏎
-// file at the top-level directory of this distribution and at⏎
-// http://rust-lang.org/COPYRIGHT.⏎
-//⏎
-// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or⏎
-// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license⏎
-// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your⏎
-// option. This file may not be copied, modified, or distributed⏎
-// except according to those terms.⏎
```

After
```
+// Copyright 2015 The Rust Project Developers. See the COPYRIGHT file at the⏎
+// top-level directory of this distribution and at⏎
+// http://rust-lang.org/COPYRIGHT. Licensed under the Apache License, Version⏎
+// 2.0 <LICENSE-APACHE or http://www.apache.org/licenses/LICENSE-2.0> or the MIT⏎
+// license <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your option.⏎
+// This file may not be copied, modified, or distributed except according to⏎
+// those terms.⏎
```

Here's [the branch](https://github.com/tikue/rustfmt/tree/line-rewrapping), for reference.

**Comment by nrc** [comment]
Interesting, I think we need some way to determine whether a comment should be wrapped or not, and wrapping unless there is a directive not to obviously won't cut it.

I wonder if there is prior art for heuristics to decide if something should be wrapped?

Worst case scenario, we have wrapping but it is off by default.

Some possible heuristics we could use (this assumes we are able to identify blocks of comments):

* only reformat if a line exceeds the width limit (after other reformatting), otherwise leave the comment alone

* maintain blank lines (e.g., in the license example) - only wrap paragraphs (text editors seem to do this)

* don't wrap multiple short lines, i.e., long, long, short would get wrapped but long, long, short, short, short would only wrap the long lines and the first short line.

* don't wrap lines which start with whitespace >1 char/tab

* don't wrap lines which start with the same character

* probably some more things....

I'm not sure we'd ever get conservative enough to allow wrapping on by default, but we might be able to.

**Comment by tikue** [comment]
Great ideas! I bet those heuristics would go a long way. Not sure if/when I'll find time to try them out, so consider this feature available if anyone else wants to have a go at this.

**Pull request merged**
