### PR TITLE
Make rewrite_string return an Option<String>

### LINKED ISSUE #217: `rewrite_string` should return `Option<String>`
Primarily so that it has a failure mode.

### PR DESCRIPTION
**Pull request by cburgdorf**
I was looking for a long hanging fruit to make myself more comfortable with the code base but I'm not sure if I interpreted the ticket correctly.

Fixes #217

### CODE REVIEW

**Comment by cburgdorf** [comment]
Ok, something doesn't seem quite right.

**Comment by nrc** [comment]
I think the tests failed because we need a rust upgrade

**Comment by marcusklaas** [comment]
I believe we are compatible with the latest rust now. This PR also needs the check mentioned in its cousin: https://github.com/nrc/rustfmt/pull/259

**Comment by cburgdorf** [comment]
Ah, I didn't notice there was someone else working on that already.

**Comment by marcusklaas** [comment]
This was implemented in https://github.com/nrc/rustfmt/pull/362. Closing.

**Pull request closed without merging**
