### PR TITLE
find_commented and fix https://github.com/nrc/rustfmt/issues/284

### PR DESCRIPTION
**Pull request by sinhpham**
Added the find_commented method and ComentFinder trait. The find_commneted should be useful in other places where we're ignoring comments.

### CODE REVIEW

**Comment by sinhpham** [comment]
It currently always rewrites the last comment in "match" in block style. I'll revisit this later.

**Comment by cassiersg** [comment]
Thanks for this PR !

I'm concerned with your method to isolate comments: the regex doesn't handle all crazy cases of comments nested, string/char litterals. We have `CharClasses`, an iterator which classifies the comment/non-comment chars in a string. It's intended to be a solid ground for all functions working with comment detection. Can you use this ?

I'm also concerned with the case where there are more than one comment after the last arm. Does it work ? A test would be welcome.

**Comment by sinhpham** [comment]
The find_commented only handles comments in code strings, string/char literals are handled by libsyntax already. That's my impression, correct me if I'm wrong.

But you're right it doesn't handle multiples comments, will fix later.

**Comment by cassiersg** [comment]
I don't understand what you mean with string/char litterals. If you look at `CharClasses` (used internally by `find_uncommented`, [here](https://github.com/nrc/rustfmt/blob/master/src/comment.rs#L208-L285)), you'll see it handles string/char litterals. Its only constraint is to know the status at the beginning of the string (ie. if we're already inside a block comment or inside a string litteral, or inside "normal" code, etc.).
I think you can easily write a function `extract_comments` that would filter chars to keep only comments.
Could it work ?

**Comment by sinhpham** [comment]
I mean that find_commented function only deals with "pure" code strings without any string literals inside, so we can have a simpler implementation using regex instead of re-parsing the whole thing and keep track of whether we're inside a string or not. In https://github.com/nrc/rustfmt/blob/master/src/expr.rs#L37-L49 we're dealing with string literals, so everything else should be pure code strings.

Rewriting the function to use CharClasses should work, but I think we don't even need the CharClasses.

**Comment by cassiersg** [comment]
I agree in this case we don't need the full machinery of `CharClasses`, since w're exploring a span where there can only be a comma, comments and a `}`. However, the regex proposed has some drawbacks:
+ It doesn't handle nested block comment, which are allowed in Rust, unlike C (`/* /* */ Here is also comment */`).
+ Since `find_comment` should be a general util function, it should handle string litteral (we might want to search for comments in `fn1("/*", /* comment */ 1)`).
+ Performance : for this simple case, regex machinery is a bit heavy, I think (unless it's compiled at build time).
+ It spreads comment detection everywhere in the code (we will probably have more functions like this) with more places for bugs...

**Comment by sinhpham** [comment]
@cassiersg good point about nested block comment, regex may not be sufficient here. However I dont think we need to handle string literals, we should always call find_commented on the string between 2 AST nodes, in your example we should be able to do something like find_commented(context.snippet(arg1.span.hi, arg2.span.lo)). I'll close this PR.

**Comment by sinhpham** [comment]
Another point regarding comment detection: I think we need it. My understanding from reading the discussion is we're waiting for libsyntax to include normal comments in the AST? If so, having a temporary find_comment would make the transition easier, and we should build format functions around that (taking pre/post comments as parameters).

Currently we're using find_uncommented and treat the string in-between as comments, and also missing comments in a few places.

**Comment by cassiersg** [comment]
I agree we don't need string litterals detection in this case. While we don't have comments in AST (which will take an unknow time, maybe infinite), we use "hacks" to deal with these.
I thinik `find_comment` is useful, I was only arguing against the implementation of it (regexes), prefering the use of CharClasses. CharClasses is meant to be a low-level tool to build high-level functions that deal with comments (see find_commented, find_comment_end, contains_comment). find_commented fits perfectly in this scheme of generic tools to work with comments.

I think this PR is very interesting, and there are some open questions with multiple comments (how to format these ?, and thus what should the signature of find_commented be ?).

I would be happy to have this in rustfmt !

**Pull request closed without merging**
