### PR TITLE
`rewrite_string` should return `Option<String>

### PR DESCRIPTION
**Pull request by posix4e**
https://github.com/nrc/rustfmt/issues/217

### CODE REVIEW

**Comment by nrc** [comment]
I think this is unnecessary complexity unless there are circumstances where `rewrite_string` could fail to format the string (which it can't at the moment). If we add such things I'd be happy to make this change then. Although it does make things more uniform with other rewrite functions, I'm not too concerned about that since they already take different arguments in some cases.

Do you have any other motivation for this change?

**Comment by posix4e** [comment]
It was solely because i saw the issue. It took me two seconds.

**Comment by nrc** [comment]
Oh, hey, I missed the issue link, sorry!

@marcusklaas what's the motivation for this?

**Comment by marcusklaas** [comment]
It can fail when the combined length of the opening sequence, closing sequence and a single character is greater than width. In other words, when width < 3. While seemingly pathological, it can and does happen, mostly in list formatting.

-----Original Message-----

**Comment by nrc** [comment]
@marcusklaas does that mean there should be `return None` in `rewrite_string` somewhere (with this PR)?

**Comment by marcusklaas** [comment]
I think so, yes.

-----Original Message-----

**Comment by posix4e** [comment]
*nod doesn't sounds to crazy

**Comment by posix4e** [comment]
I'm confused on the error case

are you talking about a short circuit at the top that does a 
    if fmt.width < 3 {
        return None;
    }

**Comment by marcusklaas** [comment]
By extension, ‘rewrite_comment` should probably return an option as well. Simply changing its signature and wrapping its calls to `rewrite_comment` should do the trick.

-----Original Message-----

**Comment by marcusklaas** [comment]
Almost, but IIRC the "opening sequences" are parameterized. While they'll be a single " most of the time, we should probably compare width to opener.len() + closer.len() + 1. I can't actually look at the code right now so apologies if this isn't making sense!

-----Original Message-----

**Comment by marcusklaas** [comment]
This was implemented in https://github.com/nrc/rustfmt/pull/362. Closing.

**Pull request closed without merging**
